Repository AY2223S1-CS2103T-W10-1/tp, pull requests merged in 2022-11, with the labels that each got.

#203 Bulk commands testing
  src/main/java/seedu/address/logic/commands/DeleteTaskAllCommand.java
  src/main/java/seedu/address/logic/parser/AssignTaskAllCommandParser.java
  src/main/java/seedu/address/logic/parser/DeleteTaskAllCommandParser.java
  src/test/java/seedu/address/logic/commands/AssignTaskAllCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteTaskAllCommandTest.java
  src/test/java/seedu/address/logic/parser/AssignTaskAllCommandParserTest.java
  src/test/java/seedu/address/logic/parser/DeleteTaskAllCommandParserTest.java
Labels: priority.Low

#193 Branch bug fixes error messages
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/AddGroupCommand.java
  src/main/java/seedu/address/logic/commands/AddGroupMemberCommand.java
  src/main/java/seedu/address/logic/commands/AddPersonCommand.java
  src/main/java/seedu/address/logic/commands/AssignTaskAllCommand.java
  src/main/java/seedu/address/logic/commands/AssignTaskCommand.java
  src/main/java/seedu/address/logic/commands/ClearCommand.java
  src/main/java/seedu/address/logic/commands/DeleteGroupCommand.java
  src/main/java/seedu/address/logic/commands/DeleteGroupMemberCommand.java
  src/main/java/seedu/address/logic/commands/DeleteTaskCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/EditPersonCommand.java
  src/main/java/seedu/address/logic/parser/AddGroupMemberCommandParser.java
  src/main/java/seedu/address/logic/parser/AssignTaskAllCommandParser.java
  src/main/java/seedu/address/logic/parser/AssignTaskCommandParser.java
  src/main/java/seedu/address/logic/parser/DeleteGroupCommandParser.java
  src/main/java/seedu/address/logic/parser/DeleteGroupMemberCommandParser.java
  src/main/java/seedu/address/logic/parser/DeleteTaskAllCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/assignment/Assignment.java
  src/main/java/seedu/address/model/group/GroupName.java
  src/main/java/seedu/address/model/person/Address.java
  src/main/java/seedu/address/model/person/Name.java
  src/main/java/seedu/address/model/person/PersonGroup.java
  src/main/java/seedu/address/model/person/Phone.java
  src/main/java/seedu/address/model/tag/Tag.java
  src/test/java/seedu/address/logic/commands/AddGroupMemberCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteGroupMemberCommandTest.java
  src/test/java/seedu/address/logic/parser/AddGroupMemberCommandParserTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/AssignTaskAllCommandParserTest.java
  src/test/java/seedu/address/logic/parser/AssignTaskCommandParserTest.java
  src/test/java/seedu/address/logic/parser/DeleteGroupCommandParserTest.java
  src/test/java/seedu/address/logic/parser/DeleteGroupMemberCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
Labels: bug, priority.Medium

#196 JavaFX Edits
  build.gradle
  src/main/resources/view/HelpWindow.fxml
  src/main/resources/view/MainWindow.fxml
Labels: priority.Medium

#207 Branch DG bug fixes
  docs/DeveloperGuide.md
  docs/diagrams/DeleteSequenceDiagram.puml
  docs/images/ArchitectureSequenceDiagram.png
  docs/images/DeleteSequenceDiagram2.png
  docs/images/LogicClassDiagram.png
  src/main/java/seedu/address/logic/commands/AssignTaskAllCommand.java
  src/main/java/seedu/address/logic/commands/EditPersonCommand.java
Labels: bug, documentation

#209 PPP update + AboutUs
  docs/AboutUs.md
  docs/team/aloynz.md
  docs/team/johndoe.md
  docs/team/tan-jin-waye.md
  docs/team/zylee348.md
Labels: documentation

#212 Update PPP and AboutUs.
  docs/AboutUs.md
  docs/team/tan-jin-waye.md
Labels: documentation

#216 Update PPP, fix checkstyle
  docs/UserGuide.md
  docs/team/cedricchia123.md
  docs/team/lianguoyang.md
  docs/team/tan-jin-waye.md
  docs/team/zylee348.md
Labels: documentation

#211 Branch UG improvements
  docs/UserGuide.md
  docs/images/user-guide/Ui.png
  docs/images/user-guide/Ui2.png
  docs/images/user-guide/Ui3 persontab.png
  docs/team/zylee348.md
Labels: documentation

#223 Modify UI component section in DG
  docs/DeveloperGuide.md
  docs/diagrams/UiClassDiagram.puml
  docs/images/UiClassDiagram.png
Labels: documentation

#221 Add test cases to Logic, Model and Storage classes
  src/test/data/JsonAddressBookStorageTest/invalidValuesPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/nullGroupAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalGroupsAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/commands/AddGroupMemberCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandResultTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/DeleteGroupMemberCommandTest.java
  src/test/java/seedu/address/logic/parser/AddGroupMemberCommandParserTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/AssignTaskAllCommandParserTest.java
  src/test/java/seedu/address/logic/parser/AssignTaskCommandParserTest.java
  src/test/java/seedu/address/logic/parser/DeleteGroupCommandParserTest.java
  src/test/java/seedu/address/logic/parser/DeleteGroupMemberCommandParserTest.java
  src/test/java/seedu/address/logic/parser/DeletePersonCommandParserTest.java
  src/test/java/seedu/address/logic/parser/DisplayGroupCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/model/UserPrefsTest.java
  src/test/java/seedu/address/model/assignment/AssignmentTest.java
  src/test/java/seedu/address/model/assignment/DeadlineTest.java
  src/test/java/seedu/address/model/assignment/WorkloadTest.java
  src/test/java/seedu/address/model/group/GroupTest.java
  src/test/java/seedu/address/model/group/UniqueGroupListTest.java
  src/test/java/seedu/address/model/person/PersonGroupTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/model/person/UniquePersonListTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/storage/JsonAddressBookStorageTest.java
  src/test/java/seedu/address/storage/JsonSerializableAddressBookTest.java
  src/test/java/seedu/address/storage/JsonUserPrefsStorageTest.java
  src/test/java/seedu/address/storage/StorageManagerTest.java
Labels: enhancement, priority.Low

#226 Update UG and png image
  docs/UserGuide.md
  docs/images/zylee348.png
Labels: documentation

#229 UG fixes
  docs/UserGuide.md
  docs/images/cedricchia123.png
  docs/team/cedricchia123.md
Labels: documentation

#234 Fix minor pdf issues
  docs/UserGuide.md
Labels: documentation

#232 Update DG
  docs/DeveloperGuide.md
Labels: documentation

#233 Fix formatting for PDF conversion
  docs/UserGuide.md
Labels: documentation
