Repository AY2223S1-CS2103T-W10-1/tp, pull requests merged in 2022-10, with the labels that each got.

#72 Add Group Support to Address Book
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/team/tan-jin-waye.md
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/AddGroupCommand.java
  src/main/java/seedu/address/logic/commands/DeleteGroupCommand.java
  src/main/java/seedu/address/logic/parser/AddGroupCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/DeleteGroupCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/ReadOnlyAddressBook.java
  src/main/java/seedu/address/model/group/Group.java
  src/main/java/seedu/address/model/group/GroupName.java
  src/main/java/seedu/address/model/group/UniqueGroupList.java
  src/main/java/seedu/address/model/group/exceptions/DuplicateGroupException.java
  src/main/java/seedu/address/model/group/exceptions/GroupNotFoundException.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/model/group/GroupNameTest.java
  src/test/java/seedu/address/model/group/GroupTest.java
  src/test/java/seedu/address/model/group/UniqueGroupListTest.java
  src/test/java/seedu/address/testutil/GroupBuilder.java
Labels: enhancement, priority.High

#87 Modify error message for addmember [dont merge yet]
  src/main/java/seedu/address/logic/commands/AddGroupMemberCommand.java
  src/main/java/seedu/address/model/person/PersonGroup.java
  src/test/java/seedu/address/logic/commands/AddGroupMemberCommandTest.java
  src/test/java/seedu/address/logic/commands/AddUserCommandTest.java
  src/test/java/seedu/address/logic/parser/AddUserCommandParserTest.java
  src/test/java/seedu/address/logic/parser/FindUserCommandParserTest.java
  src/test/java/seedu/address/model/person/PersonGroupTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
Labels: bug

#110 Update help command
  src/main/java/seedu/address/ui/CommandFeatures.java
  src/main/java/seedu/address/ui/HelpWindow.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/HelpWindow.css
  src/main/resources/view/HelpWindow.fxml
  src/main/resources/view/MainWindow.fxml
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/ui/CommandFeaturesTest.java
Labels: enhancement

#119 Update DG for assigntask command
  docs/DeveloperGuide.md
  docs/Help.png
  docs/UserGuide.md
  docs/diagrams/AssignTaskActivityDiagram.puml
  docs/images/AssignTaskActivityDiagram-AssignTaskCommand.png
Labels: documentation, priority.Medium

#120 Separate the contact details from assignments and general UI improvements
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/ui/AssignmentCard.java
  src/main/java/seedu/address/ui/AssignmentListPanel.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/java/seedu/address/ui/TabPaneManager.java
  src/main/resources/images/assignment.png
  src/main/resources/images/group.png
  src/main/resources/view/AssignmentListCard.fxml
  src/main/resources/view/AssignmentListPanel.fxml
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/PersonListCard.fxml
Labels: enhancement, priority.High

#128 Update help command with existing commands
  src/main/java/seedu/address/logic/commands/AddGroupCommand.java
  src/main/java/seedu/address/logic/commands/AddGroupMemberCommand.java
  src/main/java/seedu/address/logic/commands/AddPersonCommand.java
  src/main/java/seedu/address/logic/commands/AssignTaskAllCommand.java
  src/main/java/seedu/address/logic/commands/AssignTaskCommand.java
  src/main/java/seedu/address/logic/commands/DeleteGroupCommand.java
  src/main/java/seedu/address/logic/commands/DeleteGroupMemberCommand.java
  src/main/java/seedu/address/logic/commands/DeletePersonCommand.java
  src/main/java/seedu/address/logic/commands/DeleteTaskAllCommand.java
  src/main/java/seedu/address/logic/commands/DeleteTaskCommand.java
  src/main/java/seedu/address/logic/commands/DisplayGroupCommand.java
  src/main/java/seedu/address/logic/commands/EditPersonCommand.java
  src/main/java/seedu/address/logic/commands/FindPersonCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/ui/CommandFeatures.java
  src/main/java/seedu/address/ui/HelpWindow.java
  src/main/java/seedu/address/ui/UiManager.java
  src/main/resources/images/tabs_icon.png
  src/main/resources/view/HelpWindow.css
  src/main/resources/view/HelpWindow.fxml
  src/main/resources/view/MainWindow.fxml
  src/test/java/seedu/address/commons/util/AppUtilTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/ui/CommandFeaturesTest.java
Labels: enhancement, priority.Medium

#134 Fix table column and hyperlink for user guide.
  docs/UserGuide.md
Labels: documentation

#139 Fix bug for deletegroup command
  src/main/java/seedu/address/logic/commands/DeleteGroupCommand.java
  src/test/data/JsonSerializableAddressBookTest/typicalGroupsAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/commands/AssignTaskCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteGroupCommandTest.java
  src/test/java/seedu/address/model/group/testutil/TypicalGroups.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/model/person/testutil/TypicalPersons.java
  src/test/java/seedu/address/storage/JsonSerializableAddressBookTest.java
Labels: bug, priority.Medium

#142 Improve RGB
  src/main/java/seedu/address/model/assignment/Assignment.java
  src/main/java/seedu/address/model/assignment/Workload.java
  src/main/java/seedu/address/ui/AssignmentCard.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/test/java/seedu/address/model/person/PersonTest.java
Labels: enhancement

#149 Branch UI lightmode [merge asap before feature freeze]
  docs/DeveloperGuide.md
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/DeleteGroupCommand.java
  src/main/java/seedu/address/logic/commands/DeleteGroupMemberCommand.java
  src/main/java/seedu/address/model/UserPrefs.java
  src/main/java/seedu/address/ui/GroupCard.java
  src/main/resources/view/CommandBox.fxml
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/Extensions.css
  src/main/resources/view/GroupListCard.fxml
  src/main/resources/view/HelpWindow.css
  src/main/resources/view/MainWindow.fxml
  src/test/data/JsonUserPrefsStorageTest/ExtraValuesUserPref.json
  src/test/data/JsonUserPrefsStorageTest/TypicalUserPref.json
  src/test/java/seedu/address/storage/JsonUserPrefsStorageTest.java
Labels: bug, priority.High

#132 Branch dg updates
  docs/DeveloperGuide.md
  docs/diagrams/AddDeleteGroupState0.puml
  docs/diagrams/AddDeleteGroupState1.puml
  docs/diagrams/AddDeleteGroupState2.puml
  docs/diagrams/AddDeleteMemberState0.puml
  docs/diagrams/AddDeleteMemberState1.puml
  docs/diagrams/AddDeleteMemberState2.puml
  docs/diagrams/AssignTaskActivityDiagram.puml
  docs/diagrams/BetterModelClassDiagram.puml
  docs/diagrams/BulkAssignDeleteTaskState0.puml
  docs/diagrams/BulkAssignDeleteTaskState1.puml
  docs/diagrams/DeleteGroupCommandExecutesSequenceDiagram.puml
  docs/diagrams/DeleteGroupMemberCommandExecutesSequenceDiagram.puml
  docs/diagrams/DeleteGroupSequenceDiagram.puml
  docs/diagrams/DeleteMemberSequenceDiagram.puml
  docs/diagrams/DeleteTaskAllCommandExecuteSequenceDiagram.puml
  docs/diagrams/DeleteTaskAllSequenceDiagram.puml
  docs/diagrams/DeleteTaskCommandExecuteSequenceDiagram.puml
  docs/diagrams/DeleteTaskSequenceDiagram.puml
  docs/diagrams/DisplayGroupCommandExecutesSequenceDiagram.puml
  docs/diagrams/DisplayGroupSequenceDiagram.puml
  docs/diagrams/GroupClassDiagram.puml
  docs/diagrams/ModelClassDiagramNew.puml
  docs/diagrams/StorageClassDiagramNew.puml
  docs/images/AddDeleteGroupState0.png
  docs/images/AddDeleteGroupState1.png
  docs/images/AddDeleteGroupState2.png
  docs/images/AddDeleteMemberState0.png
  docs/images/AddDeleteMemberState1.png
  docs/images/AddDeleteMemberState2.png
  docs/images/AssignTaskActivityDiagram-AssignTaskCommand.png
  docs/images/BetterModelClassDiagram.png
  docs/images/BulkAssignDeleteTaskState0.png
  docs/images/BulkAssignDeleteTaskState1.png
  docs/images/DeleteGroupCommandExecutesSequenceDiagram.png
  docs/images/DeleteGroupMemberCommandExecutesSequenceDiagram.png
  docs/images/DeleteGroupSequenceDiagram.png
  docs/images/DeleteMemberSequenceDiagram.png
  docs/images/DeleteTaskAllCommandExecuteSequenceDiagram.png
  docs/images/DeleteTaskAllSequenceDiagram.png
  docs/images/DeleteTaskCommandExecuteSequenceDiagram.png
  docs/images/DeleteTaskSequenceDiagram.png
  docs/images/DisplayGroupCommandExecutesSequenceDiagram.png
  docs/images/DisplayGroupSequenceDiagram.png
  docs/images/GroupClassDiagram.png
  docs/images/ModelClassDiagramNew.png
  docs/images/StorageClassDiagramNew.png
Labels: documentation
